
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $gt
  local_dir: build
  on:
    branch: master